# Generated by Django 3.1.7 on 2021-03-17 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_phrasesmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phrasesmodel',
            old_name='Phrases',
            new_name='phrases',
        ),
        migrations.AlterField(
            model_name='phrasesmodel',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phrases', to='books.bookmodel'),
        ),
    ]
