# Generated by Django 3.1.7 on 2021-03-17 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210317_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phrasesmodel',
            old_name='phrases',
            new_name='phrase',
        ),
    ]
