# Generated by Django 3.1.7 on 2021-03-24 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrasesmodel',
            name='object',
            field=models.FileField(default=1, upload_to='3dObjects/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['obj', 'fbx'])]),
            preserve_default=False,
        ),
    ]
