# Generated by Django 3.1.7 on 2021-03-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0002_phrasesmodel_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrasesmodel',
            name='object',
            field=models.FileField(upload_to='3dObjects/'),
        ),
    ]
