# Generated by Django 3.1.7 on 2021-03-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0004_auto_20210330_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='author_image',
            field=models.ImageField(blank=True, default='placeholder_author.png', null=True, upload_to=''),
        ),
    ]
