# Generated by Django 3.1.7 on 2021-04-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0005_auto_20210330_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrasesmodel',
            name='object',
            field=models.FileField(blank=True, null=True, upload_to='3dObjects/'),
        ),
    ]
