# Generated by Django 3.1.7 on 2021-04-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0006_auto_20210401_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='book_cover',
            field=models.ImageField(blank=True, default='placeholder_cover.png', null=True, upload_to=''),
        ),
    ]
