# Generated by Django 3.1.7 on 2021-04-07 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0007_auto_20210401_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodel',
            name='object',
            field=models.FileField(blank=True, null=True, upload_to='3dObjects/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['obj', 'fbx'])]),
        ),
        migrations.AlterField(
            model_name='phrasesmodel',
            name='object',
            field=models.FileField(blank=True, null=True, upload_to='phrases_object/'),
        ),
    ]
