# Generated by Django 3.1.7 on 2021-04-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0009_auto_20210407_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='book_cover',
            field=models.ImageField(blank=True, default='placeholder_cover.png', null=True, upload_to='Book_Cover/'),
        ),
    ]
