# Generated by Django 3.1.7 on 2021-05-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0017_auto_20210409_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='author_image',
            field=models.ImageField(null=True, upload_to='Author_Image'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='book_cover',
            field=models.ImageField(default='placeholder_cover.png', null=True, upload_to='Book_Cover'),
        ),
    ]
