# Generated by Django 3.1.7 on 2021-05-25 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0018_auto_20210525_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodel',
            name='phrase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_phrases', to='book_api.phrasesmodel'),
        ),
        migrations.AlterField(
            model_name='phrasesmodel',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='book_api.bookmodel'),
        ),
    ]
