# Generated by Django 3.1.7 on 2021-05-25 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0019_auto_20210525_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrasesmodel',
            name='object',
            field=models.FileField(null=True, upload_to='phrases_object/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['obj', 'fbx', 'mp3', 'wav', 'jpg', 'png', 'mp4', 'mkv', 'flv', 'avi', 'm4v', 'm4p '])]),
        ),
    ]
