# Generated by Django 3.1.7 on 2021-05-25 13:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0020_auto_20210525_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='Author_Image'),
        ),
        migrations.AlterField(
            model_name='contentmodel',
            name='phrase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_phrases', to='book_api.phrasesmodel'),
        ),
        migrations.AlterField(
            model_name='phrasesmodel',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='book_api.bookmodel'),
        ),
        migrations.AlterField(
            model_name='phrasesmodel',
            name='object',
            field=models.FileField(blank=True, null=True, upload_to='phrases_object/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['obj', 'fbx', 'mp3', 'wav', 'jpg', 'png', 'mp4', 'mkv', 'flv', 'avi', 'm4v', 'm4p '])]),
        ),
    ]
